# Generated by Django 3.1.5 on 2021-01-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoDisciplinar',
            fields=[
                ('n_acao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'acao_disciplinar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('n_campeonato', models.AutoField(primary_key=True, serialize=False)),
                ('nome_campeonato', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'campeonato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('n_equipa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_equipa', models.CharField(max_length=50)),
                ('fundacao', models.IntegerField()),
                ('origem', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('descricao_equipa', models.CharField(blank=True, max_length=150, null=True)),
                ('treinador', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'equipa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('n_faixa', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'faixa_etaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('n_jogador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('data_nasc', models.DateField()),
                ('nif', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('morada', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jogador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('n_jogo', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('localizacao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_jogo', models.IntegerField()),
                ('n_jogador', models.IntegerField()),
                ('minuto', models.CharField(max_length=6)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'marcacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('n_modalidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_modalidade', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'modalidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('n_substituicao', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'substituicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAcao',
            fields=[
                ('n_tipo_acao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_acao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPontuacao',
            fields=[
                ('n_tipo_pontuacao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipo_pontuacao', models.CharField(max_length=100)),
                ('vitoria', models.IntegerField()),
                ('derrota', models.IntegerField()),
                ('empate', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_pontuacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('n_jogo', models.OneToOneField(db_column='n_jogo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.jogo')),
                ('posicao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'convocatoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('n_campeonato', models.OneToOneField(db_column='n_campeonato', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.campeonato')),
                ('ano', models.IntegerField()),
            ],
            options={
                'db_table': 'epoca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('n_equipa', models.OneToOneField(db_column='n_equipa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.equipa')),
                ('pontuacao_total', models.IntegerField()),
            ],
            options={
                'db_table': 'pontuacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadoJogo',
            fields=[
                ('n_jogo', models.OneToOneField(db_column='n_jogo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.jogo')),
                ('resultado', models.CharField(max_length=20)),
                ('pontuacao', models.CharField(max_length=20)),
                ('visitante', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'resultado_jogo',
                'managed': False,
            },
        ),
    ]
